// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xCbrJYDcC_544afpgyPcx8A9FQkWPwM',
    appId: '1:724229408606:web:97b8ccf754186a1243b1cf',
    messagingSenderId: '724229408606',
    projectId: 'e-commerce-e7feb',
    authDomain: 'e-commerce-e7feb.firebaseapp.com',
    storageBucket: 'e-commerce-e7feb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQo6aDa7sy_BXJZwt-K2TckgimBonfYA',
    appId: '1:724229408606:android:83fbcf8f5bfc9cd243b1cf',
    messagingSenderId: '724229408606',
    projectId: 'e-commerce-e7feb',
    storageBucket: 'e-commerce-e7feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NwYoeuEqLFgRJimPL0MjIIQyIcBZ_Yo',
    appId: '1:724229408606:ios:ec58f2c18d37a94643b1cf',
    messagingSenderId: '724229408606',
    projectId: 'e-commerce-e7feb',
    storageBucket: 'e-commerce-e7feb.appspot.com',
    androidClientId: '724229408606-ckj3hicbknvpe2jlhd67vp4s4ahn5kbm.apps.googleusercontent.com',
    iosClientId: '724229408606-svol7nhqe0fpgn58qvfcgq2ac2vfknfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}